"""agregando box model a base de datos

Revision ID: 26d0e5354460
Revises: 1e94f9706eec
Create Date: 2024-10-29 11:08:43.827112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d0e5354460'
down_revision = '1e94f9706eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('box_size', sa.String(length=50), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=False),
    sa.Column('engagement_fee', sa.Float(), nullable=False),
    sa.Column('delivery_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('box_requests')
    # ### end Alembic commands ###
