"""Add agreed_pickup_date field to BoxRequest

Revision ID: c327acf272ea
Revises: 35bed8c8c789
Create Date: 2024-10-31 23:39:26.475063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c327acf272ea'
down_revision = '35bed8c8c789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agreed_pickup_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box_requests', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('agreed_pickup_date')

    # ### end Alembic commands ###
